base: "https://wizley.io"

author:
  name: "Wizley"
  github: "wizley9999"

giscus:
  repo: "wizley9999/wizley9999.github.io"
  repoId: "R_kgDOOVhk4w"
  category: "General"
  categoryId: "DIC_kwDOOVhk484Co3gp"
  mapping: "pathname"
  reactionsEnabled: "1"
  inputPosition: "top"
  theme: "light"
  lang: "en"
