base: "https://wizley.io"

author:
  name: "Wizley"
  github: "wizley9999"
  identities:
    - "Y.S. Lee"
    - "Software Developer"
  tagline: "A passionate Software Developer with a focus on cybersecurity."

giscus:
  repo: "wizley9999/wizley9999.github.io"
  repoId: "R_kgDOOVhk4w"
  category: "General"
  categoryId: "DIC_kwDOOVhk484Co3gp"
  mapping: "pathname"
  reactionsEnabled: "1"
  inputPosition: "top"
  theme: "light"
  lang: "en"
